language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: nightly
          env: COMPOSER_FLAGS="--dev --ignore-platform-reqs"
    allow_failures:
        - php: nightly

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction -v
    - composer info -D | sort

script:
  - phpenv config-rm xdebug.ini || return 0
  - ./vendor/bin/phpunit --verbose
